# config.yaml

# Paths
PROJECT_DIR: "/home/toriowo/Snakemake_projects/sexfindr-snakemake/coverage-based-analyses"
MERGED_BAM_DIR: "/home/toriowo/Snakemake_projects/sexfindr-snakemake/coverage-based-analyses/resources/merged_bam_files"
SCRIPTS_DIR: "/home/toriowo/Snakemake_projects/sexfindr-snakemake/coverage-based-analyses/workflow/scripts/difcover_scripts"
OUTPUT_DIR: "/home/toriowo/Snakemake_projects/sexfindr-snakemake/coverage-based-analyses/results"

SPECIES:
  - DanubeCsikii
  - RhinePhoxinus

# Rule Toggles
RUN_SAMTOOLS_STATS: true
RUN_MULTIQC: false
RUN_MERGE_BAMS: false
RUN_COVERAGE_STATS: false
RUN_DIFCOVER: false
RUN_DNA_COPY: false
