project_dir: "/home/toriowo/SNAKEMAKE/SexDetermination_snakemake"
source_directory: "/data/raw_fastq"
species: "SeinePhoxinus"  # or a list
kmers_gwas_bin: "/path/to/kmers_gwas_bin"
tools_dir: "/path/to/tools"
threads: 10
kmer_length: 31
mac: 2
maf: 0.05
block_size: 10000
pheno_dir: "/path/to/pheno"
reference: "/path/to/reference.fasta"
